name: Build ARM Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t arm64-builder .

      - name: Build project inside Docker
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace arm64-builder bash -c "mkdir -p build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux-aarch64.cmake && make -j$(nproc)"

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: serial_port_debugger-linux-arm64
          path: build/serial_port_debugger