name: Build AMD Linux Application

on:
  push:
    branches: [main]  # 可以根据需要修改分支名称
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.12
          host: linux
          arch: desktop
          modules: qtserialport qtsql

      - name: Configure Qt Project
        run: |
          mkdir -p build  # 确保 build 目录被创建
          cd build
          qmake ../ -spec linux-g++ CONFIG+=release

      - name: Build Project
        run: |
          cd build
          make VERBOSE=1  # 使用详细模式编译，方便调试

      - name: Check Build Output
        run: |
          cd build
          ls -l  # 列出 build 目录中的所有文件，确认 SerialPortDebugger 是否生成

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Build
          path: build/
