name: Build ARM Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ARM64 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-aarch64-linux-gnu qt5-qmake libqt5serialport5-dev qtbase5-dev:arm64

      - name: Show compiler version
        run: |
          echo "Using compiler:"
          aarch64-linux-gnu-g++ --version

      - name: Print environment variables (optional)
        run: |
          echo "PATH: $PATH"
          echo "QTDIR: $QTDIR"
        env:
          QTDIR: /usr/lib/aarch64-linux-gnu/qt5

      - name: Configure CMake for ARM64
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux-aarch64.cmake
        env:
          QTDIR: /usr/lib/aarch64-linux-gnu/qt5
          PATH: ${{ runner.tool_cache }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/aarch64-linux-gnu/qt5/bin

      - name: Build project
        run: |
          cd build
          make -j$(nproc)
        env:
          QTDIR: /usr/lib/aarch64-linux-gnu/qt5
          PATH: ${{ runner.tool_cache }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/aarch64-linux-gnu/qt5/bin

      - name: Check build output
        run: |
          ls -l build

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: serial_port_debugger-linux-arm64
          path: build/serial_port_debugger