name: Qt Linux ARM Build

on: [push, pull_request]

jobs:
  build:
    name: Build Qt Project for Linux ARM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install aqtinstall==0.5.*

      - name: Install Qt for ARM
        run: |
          python3 -m aqt install -O /home/runner/work/serial_port_debugger/Qt 5.15.2 linux linux_arm64

      - name: Set up build environment
        run: |
          export PATH=/home/runner/work/serial_port_debugger/Qt/5.15.2/gcc_64/bin:$PATH
          export QTDIR=/home/runner/work/serial_port_debugger/Qt/5.15.2/gcc_64
          export LD_LIBRARY_PATH=/home/runner/work/serial_port_debugger/Qt/5.15.2/gcc_64/lib:$LD_LIBRARY_PATH

      - name: Build Qt Project
        run: |
          qmake
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: qt-build-linux-arm
          path: ./build/
